### ISSUE TITLE
Failed to install the requested application

### ISSUE THREAD

**Issue by PinYuanChen** [willhains/Kotoba#78]
I download the zip file and follow the instructions to modify values in info.plist.
But I can't build the project. It keeps showing alert with title "Failed to install the requested application" and says "The application's Info.plist does not contain a valid CFBundleVersion. Ensure your bundle contains a valid CFBundleVersion."
Does anyone have the same problem?

**Comment by movsb** [comment]
I encountered the same issue, it took me hours to address what the problem is, but I can't.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/5374525/216830814-e4d02890-d131-47a0-928a-373672a4c6d3.png">

**Comment by willhains** [comment]
@PinYuanChen @movsb Please check the targets "Kotoba" and "ShareExtension", in the "General" tab. What do you see in the "Version" and "Build" fields?

**Comment by movsb** [comment]
Hi [willhains](https://github.com/willhains), For the Kotoba, there're values.
<img width="683" alt="图片" src="https://user-images.githubusercontent.com/5374525/219853394-654f691e-28fd-488b-9b48-5dd3fc9e39df.png">

For the ShareExtension, `Build` is empty.
<img width="597" alt="图片" src="https://user-images.githubusercontent.com/5374525/219853425-d0d5c093-9218-4eac-832b-83bc2f774c0c.png">

But it doesn't work even though I fill a value.
<img width="630" alt="图片" src="https://user-images.githubusercontent.com/5374525/219853445-2b8890fe-b815-4706-88b4-63b82d4d390f.png">

And then, I tried to edit the ShareExtension's Info.plist directly using Vim, but when I click the Run again, it goes back to empty.
<img width="546" alt="图片" src="https://user-images.githubusercontent.com/5374525/219853693-0d570b46-6f41-4ad4-8bfb-eb2ed44a1840.png">

**Comment by willhains** [comment]
@movsb Thanks for the screenshots.
This might be caused by one of the Build Phases, which (sorry) assumes you are running from a cloned Git repo. I guess you downloaded the zip file?

Try this for both the "Kotoba" target, and the "ShareExtension" target:
1. Select the target, then select the "Build Phases" tab.
2. Find the "Run Script" phase that contains `buildNumber` in it.
3. Click the trash can icon to delete that build phase.
4. Go back to the "General" tab, and double-check it has values in both the "Version" and "Build" fields.

Finally, build and run.

![Screenshot showing the items described in the steps above](https://user-images.githubusercontent.com/1386812/219906095-7272fa85-5f54-4643-aa11-7b5fd01a3efa.png)

**Comment by movsb** [comment]
Yes, I downloaded the zip archive instead of cloning the entire repository.

Unfortunately, it still doesn't work. But... this time I can edit the `Info.plist` file and no background process reverts it back.

I can now run this exciting app, thanks for your great help.

**Comment by willhains** [comment]
Great!
